"use strict";
// Deterministic writer for site/data/<dataset>/*.js (data-model §3.2): a classic script whose third line starts
// with `window.FGP_DATA.<section> = ` and whose right-hand side up to the final `;` is strict JSON. Maps listed in
// `lines` are written one record per line, keys in numeric (then string) order; everything else keeps the
// insertion order the builders give it. LF endings, trailing newline.

const crypto = require("crypto");

const HEADER = "// Generated by pipeline/main.js from DB2 tables and curation/. Do not edit; re-run the generator.";

function sortKeys(keys) {
  const num = (k) => /^-?\d+$/.test(k);
  return keys.slice().sort((a, b) => {
    if (num(a) && num(b)) return +a - +b;
    if (num(a) !== num(b)) return num(a) ? -1 : 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
}

function lineMap(map) {
  const keys = sortKeys(Object.keys(map));
  if (!keys.length) return "{}";
  return "{\n" + keys.map((k) => `${JSON.stringify(k)}:${JSON.stringify(map[k])}`).join(",\n") + "\n}";
}

// obj: the section object; lines: top-level keys whose values are maps to write one record per line.
// Other top-level keys go one per line when `split` is set (small hand-curated sections), else inline.
function render(section, obj, { lines = [], split = false } = {}) {
  const parts = Object.keys(obj).map((k) => {
    const v = lines.includes(k) ? lineMap(obj[k]) : JSON.stringify(obj[k]);
    return `${JSON.stringify(k)}:${v}`;
  });
  const body = split || lines.length ? "{\n" + parts.join(",\n") + "\n}" : `{${parts.join(",")}}`;
  return `${HEADER}\nwindow.FGP_DATA = window.FGP_DATA || {};\nwindow.FGP_DATA.${section} = ${body};\n`;
}

// Inverse of render for tools and tests: strip the assignment and parse the JSON.
function parse(text) {
  const lines = text.split("\n");
  const m = /^window\.FGP_DATA\.([A-Za-z]+) = /.exec(lines[2] || "");
  if (!m) throw new Error("not a data file: line 3 must assign window.FGP_DATA.<section>");
  const rest = lines.slice(2).join("\n").slice(m[0].length).replace(/;\s*$/, "");
  return { section: m[1], value: JSON.parse(rest) };
}

// Hash over every section file except meta, in section-name order (meta.dataHash).
function dataHash(files) {
  const h = crypto.createHash("sha256");
  for (const name of Object.keys(files).filter((n) => n !== "meta").sort()) h.update(`${name}\n`).update(files[name]);
  return h.digest("hex");
}

module.exports = { render, parse, dataHash, sortKeys, HEADER };
