"use strict";
// tools/prices-default.js (docs/pricing-import.md §4, §8): runs on a synthetic Auctionator file into a scratch
// directory; the real output is gitignored and not shipped before a live scan (U3).
const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");
const fx = require("./helpers/auctionator-fixture");
const emit = require("../../pipeline/emit");
const auctionator = require("../../site/lib/auctionator");
const pricing = require("../../site/lib/pricing");
const { loadSite } = require("./helpers/load-site");
const { loadApp } = require("./helpers/load-app");

const TOOL = path.resolve(__dirname, "..", "..", "tools", "prices-default.js");
const { data } = loadSite();
const BUILD = data.meta.build, DATE = "2026-10-08", TODAY = auctionator.dayNumber(new Date(2026, 9, 8));
const LINEN = 2589, WOOL = 2592, GEAR = +Object.keys(data.items.rows)[0], STRANGER = 999999;

function file(realms) {
  const entry = (m, day, q) => new Map([["m", m], ["h", new Map([[String(day), m]])], ["l", []], ["a", new Map([[String(day), q]])]]);
  const out = {};
  for (const [label, rows] of Object.entries(realms)) out[label] = { format: "cbor", data: new Map([["version", 2], ...rows.map(([id, m, day, q]) => [String(id), entry(m, day, q)])]) };
  return fx.writeFile(out);
}
function scratch() { return fs.mkdtempSync(path.join(os.tmpdir(), "fgp-prices-")); }
function run(dir, bytes, extra) {
  const lua = path.join(dir, "Auctionator.lua");
  fs.writeFileSync(lua, bytes);
  return spawnSync(process.execPath, [TOOL, lua, "--build", BUILD, "--date", DATE, "--out", path.join(dir, "out.js"), ...(extra || [])], { encoding: "utf8" });
}

test("writes pricesDefault for the data's build: planner IDs only, sorted, deterministic, no realm name", () => {
  const dir = scratch();
  const bytes = file({ "Realm Synthetic": [[WOOL, 300, TODAY - 1, 5], [LINEN, 120, TODAY, 30], [STRANGER, 1, TODAY, 1], [GEAR, 5000, TODAY - 2, 1]] });
  const r = run(dir, bytes, ["--realm", "Realm Synthetic"]);
  assert.strictEqual(r.status, 0, r.stderr);
  assert.match(r.stdout, /3 prices for build .*1 realm\(s\); 1 rows not in the planner's data skipped/);
  const text = fs.readFileSync(path.join(dir, "out.js"), "utf8");
  assert.match(text.split("\n")[0], /^\/\/ Generated by tools\/prices-default\.js/);
  const { section, value } = emit.parse(text);
  assert.strictEqual(section, "pricesDefault");
  assert.deepStrictEqual(Object.keys(value), ["format", "source", "dataset", "build", "scanDay", "scanDate", "realms", "entries", "rows"]);
  assert.deepStrictEqual([value.build, value.dataset, value.scanDate, value.scanDay, value.realms, value.entries], [BUILD, data.meta.dataset, DATE, TODAY, 1, 3]);
  assert.deepStrictEqual(Object.keys(value.rows), [String(LINEN), String(WOOL), String(GEAR)].sort((a, b) => a - b));
  assert.deepStrictEqual(value.rows[LINEN], [120, TODAY, 30]);
  assert.doesNotMatch(text, /Realm Synthetic|Auctionator\.lua/);
  const again = run(dir, bytes, ["--realm", "Realm Synthetic"]);
  assert.strictEqual(again.status, 0);
  assert.strictEqual(fs.readFileSync(path.join(dir, "out.js"), "utf8"), text, "byte-identical across runs");
  // The page's pricer takes it as the default set: import > default > craft.
  const p = pricing.createPricer(data, { defaultSet: value }, { today: TODAY });
  assert.deepStrictEqual([p.price(LINEN).source, p.price(LINEN).copper], ["default", 120]);
  const both = pricing.createPricer(data, { defaultSet: value, imported: { rows: { [LINEN]: [99, TODAY - 5, 2] } } }, { today: TODAY });
  assert.deepStrictEqual([both.price(LINEN).source, both.price(LINEN).copper], ["ah", 99], "an import beats the default list, even older");
});

test("refuses a build mismatch and an old scan (unless --allow-old); lists realms when the choice is open", () => {
  const dir = scratch();
  const lua = path.join(dir, "Auctionator.lua");
  fs.writeFileSync(lua, file({ R: [[LINEN, 120, TODAY, 30]] }));
  const bad = spawnSync(process.execPath, [TOOL, lua, "--build", "1.60.0.1", "--date", DATE, "--out", path.join(dir, "x.js")], { encoding: "utf8" });
  assert.strictEqual(bad.status, 1);
  assert.match(bad.stderr, /not the game data's build/);
  assert.ok(!fs.existsSync(path.join(dir, "x.js")));
  const old = run(dir, file({ R: [[LINEN, 120, TODAY - 20, 30]] }));
  assert.strictEqual(old.status, 1);
  assert.match(old.stderr, /20 days before --date/);
  assert.strictEqual(run(dir, file({ R: [[LINEN, 120, TODAY - 20, 30]] }), ["--allow-old"]).status, 0, "one realm needs no --realm");
  const two = run(dir, file({ Alpha: [[LINEN, 120, TODAY, 30]], Beta: [[LINEN, 90, TODAY - 1, 3], [WOOL, 300, TODAY, 5]] }));
  assert.strictEqual(two.status, 1);
  assert.match(two.stderr, /2 realms in the file[\s\S]*Alpha\t1 entries[\s\S]*Beta\t2 entries/);
  // Two realms merged: the newest row per item wins.
  const merged = run(dir, file({ Alpha: [[LINEN, 120, TODAY, 30]], Beta: [[LINEN, 90, TODAY - 1, 3], [WOOL, 300, TODAY, 5]] }), ["--realm", "Alpha", "--realm", "Beta"]);
  assert.strictEqual(merged.status, 0, merged.stderr);
  const v = emit.parse(fs.readFileSync(path.join(dir, "out.js"), "utf8")).value;
  assert.deepStrictEqual([v.realms, v.rows[LINEN][0], v.rows[WOOL][0]], [2, 120, 300]);
  assert.strictEqual(run(dir, file({ R: [[LINEN, 1, TODAY, 1]] }), ["--realm", "Nope"]).status, 1);
  assert.strictEqual(spawnSync(process.execPath, [TOOL], { encoding: "utf8" }).status, 2, "usage");
});

test("the page without a default list and with one loaded (script added by the maintainer when it ships)", () => {
  const none = loadApp();
  assert.strictEqual(none.A.defaultSet(), null);
  const dir = scratch();
  assert.strictEqual(run(dir, file({ R: [[LINEN, 120, TODAY, 30]] })).status, 0);
  const { A, ctx } = loadApp();
  require("vm").runInContext(fs.readFileSync(path.join(dir, "out.js"), "utf8"), ctx);
  A.pricesChanged();
  assert.strictEqual(A.defaultSet().scanDate, DATE);
  assert.deepStrictEqual([A.pricer().price(LINEN).source, A.pricer().price(LINEN).copper], ["default", 120]);
  assert.match(A.viewHtml("prices"), /<dt>Default list<\/dt><dd>1 prices, scan 2026-10-08 \(1 realm\)/);
  assert.doesNotMatch(none.A.viewHtml("prices"), /Default list/);
  // A list for another build is ignored.
  ctx.FGP_DATA.pricesDefault.build = "1.60.0.1";
  A.pricesChanged();
  assert.strictEqual(A.defaultSet(), null);
  assert.strictEqual(A.pricer().price(LINEN), null);
});
