#!/usr/bin/env node
"use strict";
// Default price list from one Auctionator scan (docs/pricing-import.md §4; synthesis D31, D32, U3):
//
//   node tools/prices-default.js <Auctionator.lua> --realm <key> [--realm <key> …] --build <build> --date <YYYY-MM-DD>
//        [--data site/data/forever] [--out site/data/forever/prices-default.js] [--allow-old]
//
// Reuses the page's reader (site/lib/auctionator.js). Keeps only item IDs the planner knows (items and mats), writes
// window.FGP_DATA.pricesDefault with the metadata scan date, realm count and build only (no realm name, no file
// name), rows sorted for clean diffs. Refuses a --build that differs from the game data's, and a scan whose newest day
// is more than 14 days before --date unless --allow-old. Without --realm and with several realms it lists them and
// exits. With several --realm options the newest row per item wins (then the lower price).
// The output is not committed until a live scan exists (U3); the page loads it only once index.html references it.

const fs = require("fs");
const path = require("path");
const auctionator = require("../site/lib/auctionator");
const emit = require("../pipeline/emit");

const MAX_AGE = 14;
const HEADER = "// Generated by tools/prices-default.js from one Auctionator scan. Do not edit; re-run the tool.";
const ROOT = path.resolve(__dirname, "..");

function usage(msg) {
  if (msg) process.stderr.write(`prices-default: ${msg}\n`);
  process.stderr.write("usage: node tools/prices-default.js <Auctionator.lua> --realm <key> --build <build> --date <YYYY-MM-DD> [--data <dir>] [--out <file>] [--allow-old]\n");
  process.exit(2);
}

function args(argv) {
  const o = { realms: [], allowOld: false, file: null, data: path.join(ROOT, "site", "data", "forever"), out: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i], next = () => { if (i + 1 >= argv.length) usage(`${a} needs a value`); return argv[++i]; };
    if (a === "--realm") o.realms.push(next());
    else if (a === "--build") o.build = next();
    else if (a === "--date") o.date = next();
    else if (a === "--data") o.data = path.resolve(next());
    else if (a === "--out") o.out = path.resolve(next());
    else if (a === "--allow-old") o.allowOld = true;
    else if (a.startsWith("--")) usage(`unknown option ${a}`);
    else if (!o.file) o.file = a;
    else usage(`unexpected argument ${a}`);
  }
  if (!o.file) usage("no Auctionator file given");
  if (!o.build) usage("--build is required");
  if (!o.date || !/^\d{4}-\d{2}-\d{2}$/.test(o.date)) usage("--date YYYY-MM-DD is required");
  if (!o.out) o.out = path.join(o.data, "prices-default.js");
  return o;
}

function section(dir, name) { return emit.parse(fs.readFileSync(path.join(dir, `${name}.js`), "utf8")).value; }

function main(argv) {
  const o = args(argv);
  const meta = section(o.data, "meta"), items = section(o.data, "items").rows, mats = section(o.data, "mats").rows;
  if (o.build !== meta.build) {
    process.stderr.write(`prices-default: refusing: --build ${o.build} is not the game data's build ${meta.build}; a price list must match the data it ships with.\n`);
    return 1;
  }
  const [y, m, d] = o.date.split("-").map(Number);
  const today = auctionator.dayNumber(new Date(y, m - 1, d));
  const isKnown = (id) => Object.prototype.hasOwnProperty.call(items, id) || Object.prototype.hasOwnProperty.call(mats, id);
  const res = auctionator.readFile(new Uint8Array(fs.readFileSync(o.file)), { today, isKnown });
  if (!res.ok) { process.stderr.write(`prices-default: ${res.error.text}\n`); return 1; }
  const usable = res.realms.filter((r) => r.usable);
  let picked;
  if (!o.realms.length) {
    if (usable.length !== 1) {
      process.stderr.write(`prices-default: ${usable.length} realms in the file; pick one or more with --realm:\n`);
      for (const r of usable) process.stderr.write(`  ${r.label}\t${r.entries} entries, newest ${r.newestDay === null ? "?" : auctionator.isoDay(r.newestDay)}\n`);
      return 1;
    }
    picked = usable;
  } else {
    picked = o.realms.map((k) => {
      const r = usable.find((x) => x.label === k || x.key === k);
      if (!r) { process.stderr.write(`prices-default: no usable realm "${k}" in the file\n`); process.exit(1); }
      return r;
    });
  }
  const newest = Math.max(...picked.map((r) => (r.newestDay === null ? -Infinity : r.newestDay)));
  if (!Number.isFinite(newest)) { process.stderr.write("prices-default: the scan has no dated prices\n"); return 1; }
  if (today - newest > MAX_AGE && !o.allowOld) {
    process.stderr.write(`prices-default: refusing: the newest scan day is ${today - newest} days before --date (limit ${MAX_AGE}); pass --allow-old to override.\n`);
    return 1;
  }
  const rows = {};
  let skipped = 0;
  for (const r of picked) {
    for (const [id, row] of Object.entries(r.rows)) {
      if (!isKnown(+id)) { skipped++; continue; }
      const cur = rows[id];
      if (!cur || (row[1] || 0) > (cur[1] || 0) || ((row[1] || 0) === (cur[1] || 0) && row[0] < cur[0])) rows[id] = row;
    }
  }
  const value = {
    format: 1, source: "default", dataset: meta.dataset, build: meta.build,
    scanDay: newest, scanDate: auctionator.isoDay(newest), realms: picked.length, entries: Object.keys(rows).length, rows,
  };
  const text = emit.render("pricesDefault", value, { lines: ["rows"] }).replace(emit.HEADER, HEADER);
  fs.mkdirSync(path.dirname(o.out), { recursive: true });
  fs.writeFileSync(o.out, text);
  process.stdout.write(`prices-default: ${value.entries} prices for build ${meta.build}, scan ${value.scanDate}, ${picked.length} realm(s); ${skipped} rows not in the planner's data skipped → ${path.relative(process.cwd(), o.out)}\n`);
  return 0;
}

if (require.main === module) process.exitCode = main(process.argv.slice(2));
module.exports = { main };
